### PR TITLE
Adding assemble flag

### PR DESCRIPTION
**Pull request by kehiy**
In this PR I've added an `--assemble` flag which gives the user an assembled file of the `.asm` code.
Also, I removed some unused files and variables and fixed some warnings from Golang since it was using deprecated packages.

A `go.mod` file was also added so there is no Golang error in the `main.go` file anymore.

It can be improved by supporting running object files as well. I'll enhance the CLI in the next PRs.

### CODE REVIEW

**Comment by kehiy** [comment]
@obscuren Can you kindly review this?

**Comment by obscuren** [comment]
Why thank you! I was a little surprised to say the least when I saw this PR. This project has not seen any dev for over 8 years. 

I’ll certain review your PR :-)

**Comment by obscuren** [comment]
LGTM 

although I believe this (code base and PR changes) could benefit from the `log` package over `fmt` and `os.Exit(…)`.

**Comment by kehiy** [comment]
@obscuren Thanks, I was experimenting with this project and reading its code. that's very cool.

Also, yes I agree, `log` is a good option I can work on that too.

**Pull request merged**
